from pathlib import Path
from html import escape as e
import json, unicodedata

ROOT=Path(__file__).parent
OUT=ROOT/'dist'
ORIGIN='https://boxex-courier-redesign.gentle-mesa-8085.chatgpt.site'
def slug(s): return ''.join(c for c in unicodedata.normalize('NFD',s.lower()) if unicodedata.category(c)!='Mn').replace(' ','-')
countries={
 'Colombia':['Aéreo','Marítimo','Marítimo express'], 'Venezuela':['Aéreo','Marítimo'],
 'Ecuador':['Aéreo'],'Perú':['Aéreo'],'México':['Terrestre'],'Guatemala':['Aéreo','Marítimo','Marítimo express'],
 'El Salvador':['Aéreo','Marítimo'],'Nicaragua':['Aéreo','Marítimo'],'Honduras':['Aéreo','Marítimo'],
 'República Dominicana':['Aéreo','Marítimo'],'Haití':['Marítimo']}
services=[('envios-internacionales','Envíos internacionales','Para eso que quieres hacer llegar.','Envía paquetes, cajas y mercancías desde Estados Unidos a los destinos de Boxex. Elige la modalidad disponible para tu país con asesoría del equipo.', 'package'),('recogida-en-casa','Recogida en casa','El viaje empieza en tu puerta.','Solicita la recogida de tus paquetes en tu casa o ubicación. El equipo confirma la disponibilidad, los detalles del paquete y las condiciones antes de coordinarla.','home'),('casillero-virtual','Casillero virtual','Tus compras en USA, más cerca.','Recibe tus compras online en la dirección de Boxex en Estados Unidos y coordina su envío. Crea tu cuenta para obtener tu identificación de casillero.','bag'),('exportaciones','Exportaciones','Tu negocio puede llegar más lejos.','Recibe acompañamiento del equipo de comercio exterior para enviar mercancías desde Colombia hacia destinos internacionales.','globe')]
offices=[('Colombia','Cali','Calle 28 Norte #2 Bis N - 75','+576024867979'),('Colombia','Bogotá','Carrera 97 #24c - 75 Bodega 47','+576017457979'),('Colombia','Cartagena','Carrera 25 #25a-40','+576056932740'),('Colombia','Medellín','Calle 7S #42-70 Ofi 1513','+576046045927'),('Estados Unidos','Miami · Bodega central','2025 NW 102 Ave. #109, Doral FL 33172','+13055932152'),('Estados Unidos','Miami · Aeropuerto','2509B NW 72 Ave., Miami FL 33122','+13054363000'),('Estados Unidos','New York · Jackson Heights','88-23 37 Ave., Jackson Heights NY 11372','+17186515500'),('Estados Unidos','New York · Woodside','57-19 Roosevelt Ave., Woodside NY 11377','+17184762099'),('Estados Unidos','New Jersey · Morris Ave.','260 Morris Ave., Elizabeth NJ 07208','+19083557020'),('Estados Unidos','New Jersey · Bayway Ave.','725 Bayway Ave., Elizabeth NJ 07202','+19089629024'),('Estados Unidos','Boston','52 Bennington St., East Boston MA 02128','+16175692037'),('Estados Unidos','Texas · Houston','5013 Hwy 6 North, Houston TX 77084','+12813454610'),('Estados Unidos','Texas · Katy','21414 Julie Marie Ln., Suite 501, Katy TX 77449','+13463224160')]
faqs=[('¿A qué países puedo enviar desde Estados Unidos?','Boxex atiende Colombia, Venezuela, Ecuador, Perú, México, Guatemala, El Salvador, Nicaragua, Honduras, República Dominicana y Haití. Las modalidades cambian según el país. Consulta Destinos para elegir tu ruta.'),('¿Cómo conozco el costo de mi envío?','Prepara el país y ciudad de destino, contenido, peso y medidas de tu paquete. Solicita una cotización al equipo de Boxex para confirmar flete, cargos, cobertura y condiciones antes de enviar.'),('¿Qué es un casillero virtual?','Es una dirección en Estados Unidos para recibir tus compras online. Boxex identifica los paquetes con tu IDBOX y te acompaña en el proceso de despacho. El registro del casillero se ofrece sin costo; el transporte se cotiza por separado.'),('¿Cómo rastreo un paquete?','Usa el número de guía que recibiste de Boxex. La opción Rastrea tu envío te lleva al sistema oficial de seguimiento. El tracking de la tienda en Estados Unidos puede ser distinto de tu guía Boxex.'),('¿Pueden recoger mi caja en casa?','Boxex ofrece recogida en casa. Consulta con el equipo la disponibilidad en tu ubicación, el tamaño y contenido de tu caja y las condiciones de recogida.'),('¿Cuánto tarda en llegar?','El plazo depende del origen, destino, modalidad y proceso aduanero. Pide el tiempo estimado para tu envío específico al cotizar. No todas las rutas tienen los mismos plazos.'),('¿Qué puedo enviar?','Antes de comprar o empacar, consulta las condiciones y restricciones de Boxex y confirma tu tipo de mercancía con el equipo. Las reglas varían por producto y destino.'),('¿Cómo hago una reclamación?','Accede a Quejas y reclamos desde Ayuda. Ten a mano tu número de guía y la información del caso para diligenciar el formulario oficial.')]
icons={'package':'<path d="m3 7 9-5 9 5v10l-9 5-9-5Z M3 7l9 5 9-5 M12 12v10 M7.5 4.5l9 5v4"/>','home':'<path d="m3 11 9-8 9 8 M5 9v12h14V9 M9 21v-8h6v8"/>','bag':'<path d="M4 8h16l1 13H3Z M8 8V6a4 4 0 0 1 8 0v2"/>','globe':'<circle cx="12" cy="12" r="10"/><path d="M2 12h20 M12 2a20 20 0 0 1 0 20 20 20 0 0 1 0-20"/>','arrow':'<path d="M4 12h16 M14 6l6 6-6 6"/>','pin':'<path d="M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2"/>','search':'<circle cx="10" cy="10" r="7"/><path d="m15 15 6 6"/>','check':'<path d="m4 12 5 5L20 6"/>','plane':'<path d="m22 2-7 20-4-9-9-4Z M22 2 11 13"/>'}
def icon(name):return f'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">{icons[name]}</svg>'
def arrow():return icon('arrow')
def button(text,url,kind='primary'):return f'<a class="button {kind}" href="{url}">{text}{arrow()}</a>'
def header():return f'''<a class="skip" href="#main">Saltar al contenido</a><div class="topbar"><div class="wrap"><span>Conectamos Estados Unidos con Latinoamérica</span><div><a href="/rastreo/">Rastrea tu envío</a><a href="/pagos/">Pagos</a><a href="https://clientes.boxexpress.com/app/">Mi casillero ↗</a></div></div></div><header class="header"><div class="wrap nav"><a href="/" class="brand" aria-label="Boxex, inicio"><img src="/assets/logo.png" width="256" height="51" alt="BoxExpress y Boxex Unlimited Courier"></a><button class="menu-toggle" aria-expanded="false" aria-controls="navigation">Menú <span>☰</span></button><nav id="navigation" aria-label="Navegación principal"><a href="/servicios/">Servicios</a><a href="/destinos/">Destinos</a><a href="/como-funciona/">Cómo funciona</a><a href="/oficinas/">Oficinas</a><a href="/ayuda/">Ayuda</a>{button('Cotizar envío','/cotizar/')}</nav></div></header>'''
def footer():return '''<footer><div class="wrap footer-top"><div><img src="/assets/logo.png" width="256" height="51" alt="Boxex"><p>Personas, familias y negocios.<br>Siempre hay algo que nos une.</p></div><div><h3>Tu envío</h3><a href="/servicios/">Servicios</a><a href="/destinos/">Destinos y modalidades</a><a href="/rastreo/">Rastrear envío</a><a href="/pagos/">Pagar una orden</a></div><div><h3>Estamos cerca</h3><a href="/oficinas/">Encuentra una oficina</a><a href="/contacto/">Contacto</a><a href="/ayuda/">Preguntas frecuentes</a><a href="/guias/">Guías para enviar</a><a href="/aliados/">Sé nuestro aliado</a></div><div><h3>Boxex</h3><a href="/nosotros/">Sobre nosotros</a><a href="/legal/">Información legal</a><a href="/reclamaciones/">Quejas y reclamos</a><a href="https://controlboxexpress.com/app/login">Acceso agentes ↗</a><a href="https://www.instagram.com/boxexusa/">Instagram ↗</a></div></div><div class="wrap footer-bottom"><span>© 2026 Boxex · Unlimited Courier</span><a href="/condiciones/">Condiciones y restricciones</a><a href="https://boxexpress.com/centroaspectos-legales/">Protección de datos</a></div></footer><a class="human-help" href="https://wa.me/573176410982" aria-label="Hablar con Boxex por WhatsApp">¿Te ayudamos? <span>↗</span></a>'''
pages={}
def save(path,title,desc,body,extra_schema=None):
    pages[path]=(title,desc)
    structured=[{'@context':'https://schema.org','@type':'Organization','name':'Boxex','url':'https://boxexpress.com/','logo':ORIGIN+'/assets/logo.png','sameAs':['https://www.instagram.com/boxexusa/','https://www.facebook.com/boxexinternational/']}]
    if path: structured.append({'@context':'https://schema.org','@type':'BreadcrumbList','itemListElement':[{'@type':'ListItem','position':1,'name':'Inicio','item':ORIGIN+'/'},{'@type':'ListItem','position':2,'name':title,'item':ORIGIN+'/'+path+'/'}]})
    if extra_schema: structured.append(extra_schema)
    canonical=ORIGIN+'/'+(path+'/' if path else '')
    html=f'''<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{e(title)} | Boxex</title><meta name="description" content="{e(desc)}"><meta name="robots" content="noindex, nofollow"><link rel="canonical" href="{canonical}"><meta property="og:title" content="{e(title)} | Boxex"><meta property="og:description" content="{e(desc)}"><meta property="og:type" content="website"><meta property="og:url" content="{canonical}"><link rel="icon" href="/assets/logo.png"><link rel="stylesheet" href="/assets/styles.css"><script type="application/ld+json">{json.dumps(structured,ensure_ascii=False)}</script><script src="/assets/gsap.min.js" defer></script><script src="/assets/ScrollTrigger.min.js" defer></script><script src="/assets/app.js" defer></script></head><body>{header()}<main id="main">{body}</main>{footer()}</body></html>'''
    target=OUT/path/'index.html';target.parent.mkdir(parents=True,exist_ok=True);target.write_text(html,encoding='utf-8')
def heading(kicker,title,desc):return f'<section class="page-intro wrap"><a class="breadcrumb" href="/">Inicio / {kicker}</a><h1>{title}</h1><p>{desc}</p></section>'
def cta(title='Lo que importa, hazlo llegar.',text='Cuéntanos qué quieres enviar. Te ayudamos a elegir la opción para tu destino.'):
    return f'<section class="final-cta"><div class="wrap"><div><h2>{title}</h2><p>{text}</p></div>{button("Preparar mi envío","/cotizar/","gold")}</div></section>'
def servicecards():return '<div class="service-grid">'+''.join(f'<a class="service-card" href="/servicios/{s}/"><div class="service-icon">{icon(ic)}</div><h3>{name}</h3><p>{desc}</p><span>Conoce el servicio {arrow()}</span></a>' for s,name,tag,desc,ic in services)+'</div>'
def faqhtml(items):return '<div class="faq-list">'+''.join(f'<details><summary>{q}<span>+</span></summary><p>{a}</p></details>' for q,a in items)+'</div>'
def destinationcards():return '<div class="destination-grid">'+''.join(f'<a href="/destinos/{slug(c)}/" class="destination" data-modes="{e(" ".join(m))}"><span>{icon("pin")}<strong>{c}</strong></span><small>{" · ".join(m)}</small>{arrow()}</a>' for c,m in countries.items())+'</div>'
hero=f'''<section class="hero wrap" data-mouse-parallax><div class="hero-copy"><div class="route-tag"><span class="route-dot"></span> Desde USA. Hasta los tuyos.</div><h1>Lo que envías,<br>acerca.</h1><p>Tu familia. Tus compras. Tu próximo negocio.<br>Conectamos Estados Unidos con 11 destinos de Latinoamérica.</p><div class="hero-actions">{button('Cotizar mi envío','/cotizar/')}{button('Crear casillero','https://clientes.boxexpress.com/','secondary')}</div><div class="hero-proof"><strong>35+</strong><span>años conectando<br>lo que importa</span><i></i><strong>11</strong><span>destinos<br>en Latinoamérica</span></div></div><div class="hero-art"><div class="hero-grid" data-mouse-depth="0.015"></div><div class="orbit orbit-one" data-mouse-depth="0.02"></div><div class="orbit orbit-two" data-mouse-depth="0.035"></div><span class="art-location origin">Estados Unidos <i></i></span><div class="character-stage" data-mouse-depth="0.045"><img src="/assets/boxex-characters-hero.png" alt="Personajes Boxex en una escena 3D con una ruta internacional" loading="eager"><span class="character-note">Personajes Boxex<br><small>En movimiento</small></span></div><span class="art-location destination-label"><i></i> Más cerca de casa</span><div class="art-caption"><span>Una caja. Muchas conexiones.</span><button id="motion-toggle" aria-pressed="false">Pausar animación</button></div></div><a class="scroll-cue" href="#enviar">Descubre tu próximo envío <span>↓</span></a></section><section class="quick-actions wrap" id="enviar"><a href="/rastreo/">{icon('search')}<span><strong>¿Dónde está mi envío?</strong><small>Rastrea con tu número de guía</small></span>{arrow()}</a><a href="/servicios/recogida-en-casa/">{icon('home')}<span><strong>Recógelo en mi casa</strong><small>Consulta disponibilidad de recogida</small></span>{arrow()}</a><a href="/oficinas/">{icon('pin')}<span><strong>Encuentra tu oficina</strong><small>Direcciones y atención cercana</small></span>{arrow()}</a></section>'''
journey=f'''<section class="journey" id="recorrido"><div class="wrap journey-inner"><div class="journey-visual"><span class="eyebrow">Así de cerca</span><h2>De tus manos.<br>A su puerta.</h2><p>Un recorrido claro, desde la primera pregunta hasta la entrega.</p><div class="journey-path" aria-hidden="true"><svg viewBox="0 0 480 250"><path class="route-base" d="M40 195C130 195 70 55 185 55S270 200 365 160 410 60 445 60"/><path class="route-progress" d="M40 195C130 195 70 55 185 55S270 200 365 160 410 60 445 60"/><circle cx="40" cy="195" r="8"/><circle cx="445" cy="60" r="8"/></svg><div class="route-parcel">{icon('package')}</div><span>Origen</span><span>Destino</span></div>{button('Ver cómo funciona','/como-funciona/','secondary')}</div><div class="journey-steps">'''+''.join(f'<article class="journey-step"><span class="step-number">0{i+1}</span><div><h3>{title}</h3><p>{text}</p></div></article>' for i,(title,text) in enumerate([('Elige a dónde llegará','Consulta las modalidades disponibles para tu país y cuéntanos qué quieres enviar.'),('Prepara tu paquete','Confirma la cotización, el contenido y las condiciones. Solicita recogida o visita una oficina.'),('Déjalo en nuestras manos','El equipo te acompaña en el proceso de recepción y despacho de tu envío.'),('Sigue su recorrido','Consulta el estado con tu guía Boxex y encuentra ayuda cuando la necesites.')]))+'</div></div></section>'
home=hero+f'<section class="section wrap"><div class="section-heading"><div><span class="eyebrow">Encuentra tu forma de enviar</span><h2>Para cada conexión,<br>una solución.</h2></div><p>De una compra online a una caja para tu familia.<br>Empieza por lo que necesitas hacer.</p></div>{servicecards()}</section>'+journey+f'<section class="section wrap"><div class="section-heading"><div><span class="eyebrow">Nuestros destinos</span><h2>La distancia cambia.<br>El vínculo se queda.</h2></div><p>11 destinos desde Estados Unidos.<br>Consulta las modalidades para cada país.</p></div>{destinationcards()}</section><section class="casillero-band"><div class="wrap split"><div class="address-card"><div>{icon("bag")}<span>Tu dirección en Estados Unidos</span></div><img src="/assets/logo.png" alt="Boxex" width="240" height="48"><p>Tu IDBOX + nombre y apellido</p><strong>2025 NW 102 Ave.<br>Suite 109, Doral FL 33172</strong><span>Confirma tu IDBOX en tu cuenta antes de comprar.</span></div><div><span class="eyebrow">Casillero virtual</span><h2>Tus tiendas favoritas.<br>Tu dirección en USA.</h2><p>Crea tu casillero, recibe tu IDBOX y úsalo para identificar tus compras. Te acompañamos en el siguiente paso.</p>{button("Crear mi casillero gratis","https://clientes.boxexpress.com/")}<small>Registro sin costo. El envío se cotiza por separado.</small></div></div></section><section class="section wrap split faq-section"><div><span class="eyebrow">Antes de enviar</span><h2>Menos dudas.<br>Más tranquilidad.</h2><p>Respuestas para dar el primer paso.</p>{button("Ir al centro de ayuda","/ayuda/","secondary")}</div>{faqhtml(faqs[:4])}</section>'+cta()
save('','Envíos de Estados Unidos a Latinoamérica','Envía con Boxex a 11 destinos de Latinoamérica. Consulta servicios, casillero virtual, recogida en casa, oficinas y seguimiento.',home)
save('servicios','Servicios de envíos y logística', 'Conoce las soluciones de Boxex para paquetes, compras online y exportaciones.',heading('Servicios','¿Qué quieres hacer llegar?','Elige la solución para tu paquete, tus compras o tu negocio.')+f'<section class="wrap section no-top">{servicecards()}</section>'+cta())
for s,name,tag,desc,ic in services:
    content=heading('Servicios / '+name,tag,desc)
    content+='<section class="wrap section no-top split"><div class="content-panel"><h2>'+name+'</h2>'
    if s=='casillero-virtual':
        content+='<ol class="number-list"><li><strong>Crea tu cuenta</strong>Regístrate en el portal oficial y recibe tu IDBOX.</li><li><strong>Compra usando tu dirección</strong>Incluye tu IDBOX, nombre y la dirección de Boxex en Doral.</li><li><strong>Notifica tu compra</strong>Prealerta el tracking de la tienda desde tu cuenta.</li><li><strong>Coordina el despacho</strong>Consulta la recepción, condiciones de envío y pago en tu casillero.</li></ol>'+button('Crear casillero','https://clientes.boxexpress.com/')
    elif s=='recogida-en-casa':content+='<p>Evita desplazamientos innecesarios. Antes de coordinar la recogida, confirma tu ubicación, cantidad de cajas, peso, medidas y destino.</p><ul><li>Ten el paquete listo para su revisión.</li><li>Consulta restricciones de contenido.</li><li>Confirma disponibilidad, costo y fecha con el equipo.</li></ul>'+button('Solicitar recogida','/cotizar/?servicio=recogida')
    elif s=='exportaciones':content+='<p>Para emprendedores y empresas que necesitan enviar mercancías desde Colombia. Comparte origen, destino y descripción del producto para recibir orientación.</p><ul><li>Consulta documentos necesarios.</li><li>Confirma el peso real y las dimensiones.</li><li>Revisa responsabilidades, impuestos y condiciones del destino con el asesor.</li></ul>'+button('Consultar exportación','/cotizar/?servicio=exportacion')
    else:content+='<p>Consulta las alternativas aéreas, marítimas, marítimo express o terrestres según tu destino. Las condiciones se confirman para tu paquete.</p>'+button('Consultar mi ruta','/destinos/')
    content+='</div><aside class="aside-panel"><h2>Antes de cotizar</h2><p>Ten a mano estos datos:</p><ul><li>Ciudad de origen y destino</li><li>Contenido del envío</li><li>Peso y medidas</li><li>Cantidad de cajas o paquetes</li></ul><p>El equipo confirma el costo y el tiempo estimado según tu caso.</p>'+button('Preparar cotización','/cotizar/','secondary')+'</aside></section>'+cta()
    save('servicios/'+s,name,desc,content,{'@context':'https://schema.org','@type':'Service','name':name,'description':desc,'provider':{'@type':'Organization','name':'Boxex'}})
save('destinos','Destinos y modalidades desde Estados Unidos','Consulta los 11 destinos de Boxex y las modalidades disponibles por país.',heading('Destinos','Más cerca, país por país.','Desde Estados Unidos hacia Latinoamérica. Elige tu destino para preparar el envío.')+'<section class="wrap section no-top"><div class="filter-row" aria-label="Filtrar por modalidad"><button class="chip active" data-filter="all" aria-pressed="true">Todos</button>'+''.join(f'<button class="chip" data-filter="{m}" aria-pressed="false">{m}</button>' for m in ['Aéreo','Marítimo','Marítimo express','Terrestre'])+'</div>'+destinationcards()+'<p class="small-note">La modalidad disponible no implica un plazo ni una tarifa fija. Confirma las condiciones de tu envío antes de despacharlo.</p></section>'+cta())
for c,m in countries.items():
    desc=f'Consulta envíos de Estados Unidos a {c} con Boxex. Modalidades: '+', '.join(m)+'.'
    save('destinos/'+slug(c),'Envíos de Estados Unidos a '+c,desc,heading('Destinos / '+c,'Estados Unidos → '+c,'Tu siguiente conexión empieza aquí.')+f'<section class="wrap section no-top split"><div class="content-panel"><h2>Opciones para {c}</h2><div class="mode-list">'+''.join(f'<div>{icon("check")}<strong>{x}</strong></div>' for x in m)+f'</div><p>Prepara la ciudad de entrega, el contenido, el peso y las dimensiones. El equipo de Boxex te orienta sobre la opción para tu paquete.</p>{button("Cotizar a "+c,"/cotizar/?destino="+slug(c))}</div><aside class="aside-panel"><h2>Confirma antes de enviar</h2><ul><li>Cobertura en la ciudad de destino</li><li>Tarifa y cargos aplicables</li><li>Documentos y restricciones</li><li>Tiempo estimado de entrega</li></ul><a href="/condiciones/">Consultar condiciones</a></aside></section>'+cta(),{'@context':'https://schema.org','@type':'Service','name':'Envíos a '+c,'provider':{'@type':'Organization','name':'Boxex'},'areaServed':{'@type':'Country','name':c}})
save('como-funciona','Cómo enviar con Boxex','Prepara, cotiza y sigue tu envío con Boxex. Conoce el recorrido del paquete y del casillero.',heading('Cómo funciona','Tu envío, paso a paso.','Elige tu ruta y ten claro qué sucede después.')+journey+f'<section class="wrap section"><h2>¿Tu envío es una compra online?</h2><p>El casillero tiene su propio recorrido: registro, compra, prealerta y despacho.</p>{button("Ver cómo usar mi casillero","/servicios/casillero-virtual/")}</section>'+cta())
quote=heading('Cotizar','Empieza con tu próximo envío.','Prepara los datos y continúa con un asesor de Boxex para recibir una cotización.')+'''<section class="wrap section no-top split"><form id="quote-form" class="content-panel"><div class="form-grid"><label>¿Qué necesitas?<select name="service" id="quote-service"><option>Envío internacional</option><option>Recogida en casa</option><option>Casillero virtual</option><option>Exportación desde Colombia</option></select></label><label>País de origen<select name="origin"><option>Estados Unidos</option><option>Colombia</option></select></label><label>Ciudad de origen<input name="city" required maxlength="80" autocomplete="address-level2" placeholder="Ej. Miami"></label><label>País de destino<select name="destination" id="quote-destination">'''+''.join(f'<option value="{slug(c)}">{c}</option>' for c in countries)+'''<option value="otro">Otro destino (exportación)</option></select></label><label>Ciudad de destino<input name="toCity" required maxlength="80" placeholder="Ej. Cali"></label><label>¿Qué vas a enviar?<input name="content" required maxlength="160" placeholder="Describe los artículos"></label><label>Peso aproximado (lb)<input name="weight" type="number" min="0.1" step="0.1" placeholder="Opcional"></label><label>Medidas en cm (largo × ancho × alto)<input name="dimensions" maxlength="80" placeholder="Opcional"></label></div><p class="small-note">No se calcula un precio automático. El costo y las condiciones los confirma el equipo de Boxex.</p><button class="button primary" type="submit">Preparar consulta '''+arrow()+'''</button><div id="quote-result" class="result" aria-live="polite" hidden><h2>Tu consulta está lista</h2><p id="quote-summary"></p><a id="quote-whatsapp" class="button primary" href="https://wa.me/573176410982" target="_blank" rel="noopener">Continuar por WhatsApp ↗</a><p class="small-note">Se abrirá un mensaje preparado. Tú decides cuándo enviarlo. Aún no se ha enviado una solicitud.</p></div></form><aside class="aside-panel"><h2>El precio completo importa.</h2><p>Antes de confirmar, pide que la cotización detalle:</p><ul><li>Flete y modalidad de transporte</li><li>Cargos adicionales, si aplican</li><li>Seguro y condiciones de cobertura</li><li>Tratamiento de impuestos y aduanas</li><li>Tiempo estimado y condiciones de entrega</li></ul><p>¿Prefieres hablar directamente?</p><a href="https://wa.me/573176410982">WhatsApp de atención ↗</a></aside></section>'''
save('cotizar','Solicita una cotización de envío','Prepara origen, destino, contenido, peso y medidas para consultar una cotización con Boxex.',quote)
tracking=heading('Rastreo','Tu paquete tiene un recorrido.','Consulta su estado con tu número de guía Boxex.')+'''<section class="wrap section no-top split"><form class="content-panel" id="tracking-form" action="https://boxexpress.com/rastreo" method="get"><label>Número de guía Boxex<input name="nrogui" required pattern="[A-Za-z0-9-]{3,40}" minlength="3" maxlength="40" placeholder="Escribe tu guía" aria-describedby="tracking-help"></label><p id="tracking-help">Encontrarás la guía en la información de tu envío. No es necesariamente el tracking de la tienda.</p><button class="button primary" type="submit">Consultar en Boxex '''+arrow()+'''</button><p class="small-note">Continuarás al sistema oficial de seguimiento de Boxex.</p></form><aside class="aside-panel"><h2>¿No encuentras tu guía?</h2><p>Revisa la confirmación de tu envío o accede a tu casillero. El equipo puede orientarte si necesitas ayuda.</p>'''+button('Entrar a mi casillero','https://clientes.boxexpress.com/app/','secondary')+'''<p><a href="/contacto/">Contactar al equipo</a></p></aside></section>'''
save('rastreo','Rastrea tu envío','Accede al seguimiento oficial de Boxex con tu número de guía.',tracking)
offhtml=heading('Oficinas','Siempre hay alguien cerca.','Encuentra las direcciones y teléfonos de atención en Estados Unidos y Colombia.')+'<section class="wrap section no-top"><label class="office-search">Busca por ciudad o dirección<input id="office-search" type="search" placeholder="Miami, Cali, New York…"></label><p id="office-count" aria-live="polite">13 oficinas</p><div class="office-grid">'
from urllib.parse import quote
for country,city,address,tel in offices:
    offhtml+=f'<article class="office-card" data-search="{e(country+" "+city+" "+address)}"><span class="eyebrow">{country}</span><h2>{city}</h2><p>{address}</p><a href="tel:{tel}">{tel}</a><a href="https://www.google.com/maps/search/?api=1&query={quote(address+" "+country)}" target="_blank" rel="noopener">Ver dirección en mapa ↗</a></article>'
offhtml+='</div><p id="office-empty" hidden>No encontramos esa ciudad. <a href="/contacto/">Consulta con el equipo</a>.</p><p class="small-note">Confirma el horario y la disponibilidad del servicio antes de visitar la oficina.</p></section>'
save('oficinas','Oficinas de Boxex en Estados Unidos y Colombia','Encuentra direcciones y teléfonos de las oficinas Boxex en Miami, New York, New Jersey, Boston, Texas y Colombia.',offhtml)
save('ayuda','Centro de ayuda y preguntas frecuentes','Resuelve dudas sobre casillero, destinos, costos, rastreo, recogidas y reclamaciones.',heading('Ayuda','En cada paso, una respuesta.','Encuentra orientación para preparar y seguir tu envío.')+'<section class="wrap section no-top faq-wide">'+faqhtml(faqs)+'</section><section class="wrap help-links">'+button('Condiciones y restricciones','/condiciones/','secondary')+button('Quejas y reclamos','/reclamaciones/','secondary')+button('Hablar con Boxex','/contacto/')+'</section>',{'@context':'https://schema.org','@type':'FAQPage','mainEntity':[{'@type':'Question','name':q,'acceptedAnswer':{'@type':'Answer','text':a}} for q,a in faqs]})
save('contacto','Contacto y atención al cliente','Encuentra los canales de Boxex para consultar un envío o recibir atención.',heading('Contacto','Hablemos de lo que necesitas.','Elige un canal de atención para tu consulta.')+f'<section class="wrap section no-top help-grid"><article class="content-panel"><h2>WhatsApp</h2><p>Consulta servicios y recibe orientación.</p>{button("Hablar con un asesor","https://wa.me/573176410982")}</article><article class="content-panel"><h2>Correo electrónico</h2><p>Canal indicado en el cuestionario de Boxex.</p><a href="mailto:info@boxex.us">info@boxex.us</a></article><article class="content-panel"><h2>Atención en oficina</h2><p>Encuentra la sede más conveniente para ti.</p>{button("Buscar oficina","/oficinas/","secondary")}</article></section>')
save('pagos','Pagos de envíos Boxex','Continúa al sistema oficial de pagos de Boxex con tu número de orden.',heading('Pagos','Tu orden, en el canal correcto.','Ten a mano el número de orden asignado a tu envío.')+f'<section class="wrap section no-top split"><div class="content-panel"><h2>Continúa al portal oficial</h2><p>Consulta los medios disponibles en Boxex y sigue las instrucciones de tu orden. El despacho depende de la confirmación del pago según las condiciones del servicio.</p>{button("Ir a pagos Boxex","https://boxexpress.com/pagos/")}</div><aside class="aside-panel"><h2>¿Necesitas ayuda con un pago?</h2><p>Conserva tu número de orden y comprobante para consultar al equipo.</p><a href="/contacto/">Contactar a Boxex</a></aside></section>')
save('reclamaciones','Quejas y reclamos','Accede al formulario oficial de quejas y reclamos de Boxex.',heading('Ayuda / Reclamaciones','Queremos conocer tu caso.','Ten a mano la guía y los datos del envío para facilitar la atención.')+f'<section class="wrap section no-top"><div class="content-panel narrow"><h2>Registra tu reclamación</h2><p>Continúa al formulario oficial de Boxex. Describe lo ocurrido y conserva la constancia que entregue el sistema.</p>{button("Abrir formulario oficial","https://boxexpress.com/quejas-y-reclamos/")}</div></section>')
save('condiciones','Condiciones y restricciones de envío','Consulta las condiciones oficiales de Boxex y confirma los requisitos de tu mercancía antes de enviar.',heading('Ayuda / Condiciones','Un buen envío empieza informado.','Revisa las condiciones antes de comprar, empacar o despachar.')+f'<section class="wrap section no-top split"><div class="content-panel"><h2>Consulta tu contenido y destino</h2><p>Las restricciones y requisitos dependen de la mercancía, del país y de la modalidad. Confirma con Boxex si tu paquete puede viajar y qué documentos requiere.</p>{button("Leer condiciones oficiales","https://boxexpress.com/condiciones-restricciones/")}</div><aside class="aside-panel"><h2>Prepara tu consulta</h2><ul><li>Descripción exacta del producto</li><li>Cantidad y valor declarado</li><li>Peso y dimensiones</li><li>País y ciudad de destino</li></ul><a href="/cotizar/">Consultar con un asesor</a></aside></section>')
save('legal','Información legal de Boxex','Accede a las políticas, condiciones y documentos oficiales de Boxex.',heading('Información legal','Información para una relación clara.','Consulta las políticas y documentos publicados por Boxex.')+f'<section class="wrap section no-top"><div class="content-panel narrow"><h2>Documentos oficiales</h2><p>El centro legal reúne el contrato de prestación de servicios, derechos y deberes, política de datos y documentos de cumplimiento de Boxex.</p>{button("Abrir centro legal de Boxex","https://boxexpress.com/centroaspectos-legales/")}</div></section>')
save('aliados','Red de aliados y agentes Boxex','Conoce el canal oficial para solicitar vinculación a la red de agentes Boxex.',heading('Aliados','Conectemos más oportunidades.','Consulta cómo solicitar tu vinculación a la red de agentes autorizados Boxex.')+f'<section class="wrap section no-top"><div class="content-panel narrow"><h2>Presenta tu solicitud</h2><p>Completa el formulario oficial para que el equipo evalúe tu solicitud y te explique las condiciones de vinculación.</p>{button("Solicitar información para ser aliado","https://boxexpress.com/hagase-nuestro-agente/")}</div></section>')
save('nosotros','Sobre Boxex','Boxex conecta personas, familias y empresas mediante soluciones de courier y envíos internacionales.',heading('Sobre Boxex','Conectar es lo que nos mueve.','Más de 35 años de experiencia en logística, courier y envíos internacionales.')+f'<section class="wrap section no-top split"><div class="content-panel"><h2>Personas detrás de cada paquete.</h2><p>Boxex facilita el envío de paquetes, documentos y mercancías entre Estados Unidos, Colombia y otros destinos de Latinoamérica.</p><p>Casillero virtual, envíos internacionales, recogida en casa y acompañamiento en exportaciones forman parte de las soluciones de la compañía.</p></div><aside class="aside-panel"><h2>Familias y negocios</h2><p>Un regalo para alguien cercano. Una compra online. Productos para un emprendimiento. El equipo te orienta para preparar tu envío.</p>{button("Conoce nuestros servicios","/servicios/","secondary")}</aside></section>'+cta())
guides=[('preparar-envio','Cómo preparar tu primer envío','Una guía antes de entregar tu paquete.', [('Define tu destino','Identifica el país y la ciudad. Consulta la modalidad disponible y pregunta por cobertura en la dirección de entrega.'),('Describe el contenido','Indica qué contiene, cuántas unidades son y su valor. Antes de comprar, consulta si hay restricciones.'),('Mide y pesa','Anota peso y dimensiones de cada caja. Son datos que el asesor necesita para cotizar.'),('Confirma las condiciones','Revisa costo, cargos, seguro, tiempo estimado y documentos con el equipo antes del despacho.')]),('casillero-usa','Cómo usar tu casillero en Estados Unidos','Del registro a la prealerta de tu compra.', [('Obtén tu IDBOX','Regístrate en la plataforma oficial. Tu identificación permite asociar tus compras a tu cuenta.'),('Usa la dirección de tu cuenta','Incluye IDBOX, nombre y apellido junto a la dirección indicada por Boxex. Confírmala antes de finalizar la compra.'),('Notifica la compra','Cuando la tienda te entregue el tracking, ingresa a tu cuenta y registra la información de la compra.'),('Revisa la recepción','Consulta las notificaciones de Boxex y coordina el despacho desde el portal y con el equipo.')])]
save('guias','Guías para comprar y enviar','Aprende a preparar tu envío y a usar el casillero de Boxex.',heading('Guías','Envía con más claridad.','Orientación práctica para tu primer envío y tus compras online.')+'<section class="wrap section no-top help-grid">'+''.join(f'<article class="content-panel"><h2>{title}</h2><p>{desc}</p>{button("Leer guía","/guias/"+s+"/","secondary")}</article>' for s,title,desc,parts in guides)+'</section>')
for s,title,desc,parts in guides:
    save('guias/'+s,title,desc,heading('Guías',title,desc)+'<article class="wrap article-body">'+''.join(f'<h2>{i+1}. {h}</h2><p>{p}</p>' for i,(h,p) in enumerate(parts))+'<p class="small-note">Revisión editorial: 14 de septiembre de 2026. Fuentes: cuestionario de Boxex y <a href="https://boxexpress.com/servicios-y-condiciones/">servicios oficiales</a>. Confirma las condiciones aplicables a tu caso.</p></article>'+cta())
(OUT/'robots.txt').write_text('User-agent: *\nDisallow: /\n',encoding='utf-8')
(OUT/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join('<url><loc>'+ORIGIN+'/'+(p+'/' if p else '')+'</loc></url>' for p in pages)+'</urlset>',encoding='utf-8')
(ROOT/'routes.json').write_text(json.dumps(pages,ensure_ascii=False,indent=2),encoding='utf-8')
(OUT/'404.html').write_text('<!doctype html><html lang="es"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Página no encontrada | Boxex</title><link rel="stylesheet" href="/assets/styles.css"><main class="wrap page-intro"><h1>Este camino no existe.</h1><p>Vuelve al inicio para encontrar servicios, destinos y ayuda.</p><a class="button primary" href="/">Volver al inicio</a></main></html>',encoding='utf-8')
print(f'Generated {len(pages)} pages')

